# The serial port to use:
port: '/dev/ttyUSB0'
settings_file_path: '/home/pi/settings.txt'

# list of observables to expect from the get_all function call
# The returned dict will use those as keys. Order matters.
get_all_fields:
  - pressure
  - flow
  - o2
  - bpm
  - tidal
  - peep
  - temperature
  - battery_powered
  - battery_charge
  - peak
  - total_inspired_volume
  - total_expired_volume
  - volume_minute

# Conversion factors to apply to the values from the get_all
conversions:
    pressure: 1.01972 # mbar to cmH2O
    peak: 1.01972 # mbar to cmH2O

# watchdog reset interval time in seconds
wdinterval: 1

# Time interval used to check for alarms
alarminterval: 1

# Time [ms] required to hold down UNLOCK before screen is unlocked
unlockscreen_interval: 2000
# Unlock code: must use digits from 1-5
unlockscreen_code: "32115"

# Number of samples to display in the graphs:
nsamples: 100

# time in seconds between two data retrieval
sampling_interval: 0.1

# time in seconds between two status checks
status_sampling_interval: 0.5

# number of samples used for the y-axes plot autoscale feature (default:
# 200)
historic_nsamples: 200
# The parameters that can be set on the ESP
# The values below must match those used in the ESP
esp_settable_param:
    respiratory_rate:  'rate'
    insp_expir_ratio:  'ratio'
    insp_pressure:     'ptarget'
    pressure_trigger:  'assist_ptrigger'
    flow_trigger:      'assist_flow_min'
    support_pressure:  'pressure_support'
    enable_backup:     'backup_enable'
    max_apnea_time:    'backup_min_time'
    lung_recruit_pres: 'pause_lg_p'
    lung_recruit_time: 'pause_lg_time'
    pcv_trigger_pressure: 'pcv_trigger'
    pcv_trigger_enable: 'pcv_trigger_enable'


# This is the string returned by the ESP in case of success
return_success_code: 'OK'

# The interval used to send 1 to the ESP if expiration or espiration 
# paused button is pressed (in seconds)
expinsp_setinterval: 0.1 

# Thickness of the lines drawn in the plots
line_width: 1

# The widht of the line that draws the axes
axis_line_width: 1

# The color used to draw the axes
axis_line_color: "rgb(255,228,181)"

# Minimum number of Y axis major (labeled) ticks
n_major_ticks: 4

# Minimum number of minor (unlabeled) ticks
n_minor_ticks: 5

# The width where the Y axis lable and ticks are
left_ax_label_space: 60

# Shows the values that will trigger the alarms directly on the plots
show_safe_ranges_on_graphs: True

# Toggles the x axis labels in the graphs (specifcally, the 'Time [s]' label)
show_x_axis_labels: True

# Toggles the x axis ticks in the graphs (specifcally, the numbers on the x axis)
show_x_axis_ticks: True

# Toggles between scrolling plots and looping plots
use_looping_plots: True

# Control Start/Stop Auto/Man behavior
start_mode_timeout: 2000 # [ms] between pressing Start and allowing Stop (max 3000)


# Setup monitors (key value monitor_* must match widget name in mainwindow.ui)
# Variables to display in the graphs are in plot_var 
# and the must match names in the ESP or an available function
#
#
# Monitors are defined by the following parameters:
#
# name: The displayed, labelled name of the monitor.
# init: The initial value of the monitor before updated.
# step: (Optional, default 1) The minimum change measured by the monitor.
# dec_precision: (Optional, default 0) The number of decimal positions to display.
# units: (Optional) The displayed units
# observable: Reference to the data type that the monitor is displayed (ref. "get_all_fields" above")
# alarmcolor: (Optional, default red) The color that the monitor will turn on alarm.
# color: (Optional, default white) The text color of the monitor.
# disp_type: (Optional) The alternate display type of the monitor.
#       None: Display auto scaling text.
#       bar [low] [high]: Show a progress bar with minimum [low] and maximum [high].
monitors:
    total_inspired_volume: 
        name: "V<sub>tidal</sub>"
        init: 100
        step: 1
        dec_precision: 0
        units: "[ml]"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: total_inspired_volume

    volume_minute: 
        name: "V<sub>E</sub>"
        init: 100
        step: 1
        dec_precision: 1
        units: "[slpm]"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: volume_minute

    beats_per_minute: 
        name: "Meas. RR"
        init: 60
        step: 1
        units: "[bpm]"
        dec_precision: 0
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: bpm

    peep: 
        name: "PEEP"
        init: 60
        step: 1
        units: "[cmH<sub>2</sub>O]"
        dec_precision: 0
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: peep

    battery_charge: 
        name: "Battery [%]"
        init: 100 
        step: 1
        units: null
        dec_precision: 0
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: battery_charge
        disp_type: "bar 0 100"

    battery_powered: 
        name: "Power Source"
        init: 100 
        step: 1
        map:
          0: "AC"
          1: "Battery"
        units: null
        dec_precision: 0
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: battery_powered

    #flow: 
    #    name: "Flow"
    #    init: 10
    #    step: 1
    #    dec_precision: 0
    #    units: "[slpm]"
    #    color: "rgb(255,255,255)"
    #    alarmcolor: "red"
    #    observable: flow

    oxygen_concentration: 
        name: "FiO<sub>2</sub>" 
        init: 40
        step: 1
        dec_precision: 0
        units: "[%]"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: o2

    temperature: 
        name: "Temperature" 
        init: 40
        step: 1
        dec_precision: 0
        units: "[°C]"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: temperature

    peak: 
        name: "Max P<sub>insp</sub>" 
        init: 40
        step: 1
        dec_precision: 0
        units: "[cmH<sub>2</sub>O]"
        color: "rgb(255,255,255)"
        alarmcolor: "red"
        observable: peak

displayed_monitors:
    - battery_charge
    - battery_powered
    - beats_per_minute
    - peak
    - peep
    - total_inspired_volume
    - volume_minute
    - oxygen_concentration

alarms:
    o2:
        min: 17
        max: 100 
        setmin: 21
        setmax: 100
        under_threshold_code: 65536
        over_threshold_code: 131072
        observable: o2
        linked_monitor: oxygen_concentration
    
    #flow:
    #    min: -300
    #    max: 300
    #    under_threshold_code: 1024
    #    over_threshold_code: 2048
    #    observable: flow
    #    linked_monitor: flow

    tidal_volume:
        min: -10
        max: 1500
        under_threshold_code: 16384
        over_threshold_code: 32768
        observable: total_inspired_volume
        linked_monitor: total_inspired_volume

    bpm:
        min: 0
        max: 17
        under_threshold_code: 1048576
        over_threshold_code: 2097152
        observable: bpm
        linked_monitor: beats_per_minute

    peep:
        min: -30
        max: 30
        under_threshold_code: 262144
        over_threshold_code: 524288
        observable: peep
        linked_monitor: peep

    battery_charge:
        min: 10
        max: null
        under_threshold_code: 16
        over_threshold_code: null
        observable: battery_charge
        linked_monitor: battery_charge

    peak:
      min: 5
      max: 70
      under_threshold_code: 1
      over_threshold_code: 1
      observable: peak
      linked_monitor: peak

    vrate:
      min: 2
      max: 40
      under_threshold_code: 1
      over_threshold_code: 1
      observable: volume_minute
      linked_monitor: volume_minute

plots:
    plot_top: 
        name: "PAW"
        min: 10
        max: 80
        units: "[cmH<sub>2</sub>O]"
        color: "rgb(255,255,0)"
        observable: pressure

    plot_mid: 
        name: "V<sub>tidal</sub>"
        min: 50
        max: 1500
        units: "[ml]"
        color: "rgb(50,205,50)"
        observable: tidal

    plot_bot: 
        name: "Flow"
        min: 2 
        max: 20
        units: "[slpm]"
        color: "rgb(0,255,255)"
        observable: flow
#
# PCV Mode
#
# Note: can only have max 6 presets for now.

# Respiration Rate (breaths per minute)
respiratory_rate:
    name: "Resp. Rate"
    default: 12
    min: 4
    max: 60
    step: 1
    current: None
    units: "b/min"
    presets:
        - [5, '']
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']

# Inspiration/Expiration
insp_expir_ratio:
    # NOTE: this value is always the inverse of the fruction
    name: "Insp./Expir."
    default: 2
    min: 1
    max: 4
    step: 0.1
    current: None
    units: "ratio"
    show_fraction: True
    presets:
      - [1, '1:1'] # 1:1
      - [2, '1:2'] # 1:2
      - [3, '1:3'] # 1:3
      - [4, '1:4'] # 1:4

# Inspiratory Pressure
insp_pressure:
    name: "Insp. Pressure"
    default:  15
    min: 2
    max: 40
    step: 1
    current: None
    units: "[cmH<sub>2</sub>O]"
    conversion: 0.980665 # From cmH2O to mbar
    presets:
        - [5, '']
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']

# PEEP (auto mode)
#peep_auto:
#    name: "PEEP (Auto)"
#    default:  7.5
#    min: 0
#    max: 20
#    current: None
#    units: "mbar"
#    conversion: 0.980665 # From cmH2O to mbar
#    presets:
#        - [2, '']
#        - [5, '']
#        - [7.5, '']
#        - [10, '']
#        - [15, '']


#
# PSV Mode
#
# Note: can only have max 6 presets for now.

# The trigger that starts the respiration
pressure_trigger: 
    name: "Pressure Trigger"
    default: 1.
    min: 0.
    max: 10.
    step: 1
    current: None
    presets:
        - [8, 'Hard']
        - [6, 'Medium']
        - [3, 'Normal']
        - [1, 'Soft']


# Flow Trigger
flow_trigger: 
    name: "Flow Trigger"
    default: 30.
    min: 0.
    max: 50.
    step: 1
    current: None
    presets:
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']
        - [35, '']

# Support Pressure
support_pressure:
    name: "Support Pressure"
    default: 10.
    min: 2.
    max: 40.
    step: 1
    current: None
    units: "[cmH<sub>2</sub>O]"
    conversion: 0.980665 # From cmH2O to mbar
    presets:
        - [5, '']
        - [10, '']
        - [15, '']
        - [20, '']
        - [25, '']
        - [30, '']

# PEEP Assist
#peep_assist:
#    name: "PEEP (Assist)"
#    default: 7.5
#    min: 0.
#    max: 20.
#    current: None
#    units: "mbar"
#    presets:
#        - [2, '']
#        - [5, '']
#        - [7.5, '']
#        - [10, '']
#        - [15, '']

# Minimal Respiratory Rate
max_apnea_time:
    default: 5
    min: 2
    max: 20.
    step: 1
    current: None
    presets:
        - [3, '']
        - [5, '']
        - [10, '']
        - [15, '']


# Enable backup
enable_backup: 
  default: 1
  current: None
  presets:
    - [1, "Enabled"]
    - [0, "Disabled"]


# PCV trigger pressure
pcv_trigger_pressure:
  default: 5
  min: 0
  max: 15.
  step: 1
  conversion: 0.980665 # From cmH2O to mbar
  current: None
  presets:
    - [3, '']
    - [5, '']
    - [10, '']
    - [15, '']

# Enable PCV trigger
pcv_trigger_enable: 
  default: 1
  current: None
  presets:
    - [1, "Enabled"]
    - [0, "Disabled"]

# Lung rectruitment
lung_recruit_pres:
  default: 20
  min: 0
  max: 40
  step: 1
  current: 20
  conversion: 0.980665 # From cmH2O to mbar
  presets:
    - [0, 'None']
    - [20, 'default']
    - [40, 'max']

lung_recruit_time:
  default: 10
  min: 1
  max: 30
  step: 1
  current: 10
  presets:
    - [1, 'min']
    - [10, 'default']
    - [20, '']
    - [30, 'max']
